# Generated by Django 5.2.1 on 2025-06-01 15:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
