# Generated by Django 5.2.1 on 2025-05-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_date_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='ratings',
        ),
    ]
